FROM node:20-alpine AS builder

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires pour installer les dépendances
COPY package.json tsconfig.json ./

# Installer les dépendances
RUN npm install

# Copier le code source
COPY ./src ./src

# Compiler le code TypeScript
RUN npm run build